### ISSUE TITLE
编译问题咨询

### ISSUE THREAD

**Issue by LX2035** [bigbugcc/Openwrt#4]
time: package/feeds/packages/nps/compile#0.14#0.09#693.97
    ERROR: package/feeds/packages/nps failed to build.
package/Makefile:114: recipe for target 'package/feeds/packages/nps/compile' failed
make[2]: *** [package/feeds/packages/nps/compile] Error 1
go: downloading github.com/fatedier/golib v0.1.1-0.20220321042308-c306138b83ac
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/hashicorp/yamux v0.1.1
go: downloading github.com/quic-go/quic-go v0.32.0
go: downloading github.com/coreos/go-oidc/v3 v3.4.0
go: downloading golang.org/x/oauth2 v0.3.0
go: downloading github.com/go-playground/validator/v10 v10.11.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/fatedier/beego v0.0.0-20171024143340-6c6a4f5bd5eb
go: downloading github.com/prometheus/client_golang v1.13.0
go: downloading github.com/pires/go-proxyproto v0.6.2
go: downloading golang.org/x/time v0.0.0-20220210224613-90d013bbcef8
go: downloading github.com/fatedier/kcp-go v2.0.4-0.20190803094908-fe8645b0a904+incompatible
go: downloading golang.org/x/net v0.4.0
go: downloading github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
github.com/Azure/go-ntlmssp@v0.0.0-20200615164410-66371956d46c: Get "https://proxy.golang.org/github.com/%21azure/go-ntlmssp/@v/v0.0.0-20200615164410-66371956d46c.mod": dial tcp 142.251.43.17:443: connect: connection refused

Building targets
no Go files in /home/lx/Openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/frp-0.47.0/.go_work/build

Makefile:64: recipe for target '/home/lx/Openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/frp-0.47.0/.built' failed
make[3]: *** [/home/lx/Openwrt/lede/build_dir/target-aarch64_cortex-a53_musl/frp-0.47.0/.built] Error 1
make[3]: Leaving directory '/home/lx/Openwrt/lede/feeds/packages/net/frp'
time: package/feeds/packages/frp/compile#0.17#0.08#904.52
    ERROR: package/feeds/packages/frp failed to build.
package/Makefile:114: recipe for target 'package/feeds/packages/frp/compile' failed
make[2]: *** [package/feeds/packages/frp/compile] Error 1
make[2]: Leaving directory '/home/lx/Openwrt/lede'
package/Makefile:110: recipe for target '/home/lx/Openwrt/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: *** [/home/lx/Openwrt/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lx/Openwrt/lede'
Build failed - please re-run with -j1 to see the real error message
/home/lx/Openwrt/lede/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 1
/home/lx/Openwrt/lede/make.sh: line 72: break: only meaningful in a `for', `while', or `until' loop

编译到这里会报错，似乎是链接拉取不到，请问可以提供一点解决的思路吗？

**Comment by bigbugcc** [comment]
编译时需全局科学上网

**Comment by LX2035** [comment]
是全局科学上网的，但还是报错了，怀疑是不是新的包有什么问题呢？请问可以把一个能正常编译的包clean一下然后打包发给我试试嘛😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月27日(周四) 上午9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bigbugcc/Openwrt] 编译问题咨询 (Issue #4)




 
编译时需全局科学上网

**Comment by bigbugcc** [comment]
看日志大概率就是代理导致的，本地已经没有编译环境了😂，使用[云编译](https://github.com/bigbugcc/OpenWrts) 就没有代理这些问题。
